direction: right

title: |md
  # Module overview: platform usage analysis
| {near: top-center}

geor: geOrchestra usage activity

tsdb: Storage (DB) {
  shape: cylinder
}

superset: Dashboards of platform usage (analytics) {
  shape: image
  icon: imgs/superset.png
  width: 400
}

geor -> tsdb -> superset
