{{- $webapp := .Values.vector -}}
{{- if $webapp.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "analytics.fullname" . }}-vector-config
  labels:
    {{- include "analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-vector
data:
  vector.yaml: |-
    {{- with $webapp.config }}
      {{- . | nindent 4 }}
    {{- end }}
{{- end }}