{{- $webapp := .Values.vector -}}
{{- if $webapp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics.fullname" . }}-vector-svc
  labels:
    {{- include "analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-vector
spec:
  ports:
    - name: gprc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: api
      port: 8686
      targetPort: 8686
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-vector

{{- end }}
