# Use postgres/example user/password credentials
version: '3.1'

volumes:
  postgis_data:

services:
  db:
    image: postgis/postgis
    ports: 
      - "55432:5432"
    restart: always
    environment:
      POSTGRES_USER: georchestra
      POSTGRES_PASSWORD: georchestra
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./logs_table_init.sql:/docker-entrypoint-initdb.d/logs_table_init.sql
