# Use postgres/example user/password credentials
version: '3.1'

volumes:
  timescaledb_data:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports: 
      - "55432:5432"
    restart: always
    environment:
      POSTGRES_USER: georchestra
      POSTGRES_PASSWORD: georchestra
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./logs_table_init.sql:/docker-entrypoint-initdb.d/20-logs_table_init.sql
