{{- $webapp := .Values.timescaledb -}}
{{- if $webapp.builtin -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics.fullname" . }}-timescaledb-svc
  labels:
    {{- include "analytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-timescaledb
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ include "analytics.fullname" . }}-timescaledb

{{- end }}
